name: My Workflow

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: Step 1
        run: echo "This is step 1"

      - name: Step 2
        run: echo "TEST=111" >> $GITHUB_ENV
    outputs:
      TEST: ${{ env.TEST }}
      
  job11:
    runs-on: ubuntu-latest
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: larryon
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

  job2:
    runs-on: ubuntu-latest
    needs: job11
    steps: 
      - name: Job 2 Step 1
        run: echo "This is step 1 from job2"

      - name: Step 2
        run: echo "${{ needs.job1.outputs.TEST }}"

 
