name: My Workflow

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: Step 1
        run: echo "This is step 1"

      - name: Step 2
        run: echo "TEST=111" >> $GITHUB_ENV
    outputs:
      TEST: ${{ env.TEST }}
      
  job11:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ steps.generate_token.outputs.token }}
          approvers: myteam
          minimum-approvals: 1

  job2:
    runs-on: ubuntu-latest
    needs: job11
    steps: 
      - name: Job 2 Step 1
        run: echo "This is step 1 from job2"

      - name: Step 2
        run: echo "${{ needs.job1.outputs.TEST }}"

 
