name: main
on:
  workflow_dispatch:
    inputs:
      releaseEnv:
        type: choice
        description: 'What Env to release'
        required: true
        options:
        - dev
        - test
        - staging
        - prod

jobs:
  Deploy_dev:
    name: "Dev deploy"
    environment: dev
    runs-on: ubuntu-latest
    if: github.event.inputs.releaseEnv == 'dev'
    steps:
      - name: Deploy
        run: echo Deploying to dev
  Deploy_test:
    name: "Test deploy"
    environment: test
    if: github.event.inputs.releaseEnv == 'test'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Deploying to test
  Deploy_staging:
    name: "Staging Deploy"
    environment: staging
    if: github.event.inputs.releaseEnv == 'staging'
    needs: [Deploy_test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Deploying to Staging
  Deploy_prod:
    name: "Prod Deploy"
    environment: Prod
    if: github.event.inputs.releaseEnv == 'Prod'
    needs: [Deploy_test,Deploy_staging]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Deploying to Prod
