name: main
on:
  workflow_dispatch:
    inputs:
      releaseEnv:
        type: environment
        description: 'What Env to release'
        required: true
      version:
        required: true
jobs:
  Deploy_dev:
    name: "Dev deploy - version ${{  github.event.inputs.version }} "
    environment: dev
    if: github.event.inputs.releaseEnv == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Deploying to dev
  Deploy_test:
    name: "Test deploy"
    environment: test
    if: github.event.inputs.releaseEnv == 'test' || github.event.inputs.releaseEnv == 'prod' || github.event.inputs.releaseEnv == 'Staging'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Deploying to test
  Deploy_staging:
    name: "Staging Deploy"
    environment: staging
    if: github.event.inputs.releaseEnv == 'staging' || github.event.inputs.releaseEnv == 'prod'
    needs: [Deploy_test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Deploying to Staging
  Deploy_prod:
    name: "Prod Deploy"
    environment: prod
    if: github.event.inputs.releaseEnv == 'prod'
    runs-on: ubuntu-latest
    needs: [Deploy_staging,Deploy_test]
    steps:
      - name: Deploy
        run: echo Deploying to prod
