name: main
on:
  workflow_dispatch:

jobs:
  Deploy_test:
    name: "Test deploy"
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo Deploying to test
  Deploy_staging:
    name: "Staging Deploy"
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo Deploying to Staging
  Deploy_prod:
    name: "Prod Deploy"
    environment: Prod
    needs: [Deploy_test,Deploy_staging]
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo Deploying to Prod
