name: main
on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'What ENv to release'
        required: true
        default: 'test'

jobs:
  Deploy_dev:
    name: "Dev deploy"
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Deploying to dev
  Deploy_test:
    name: "Test deploy"
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Deploying to test
  Deploy_staging:
    name: "Staging Deploy"
    environment: staging
    needs: [Deploy_test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Deploying to Staging
  Deploy_prod:
    name: "Prod Deploy"
    environment: Prod
    needs: [Deploy_test,Deploy_staging]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Deploying to Prod
