name: My Workflow

on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Step 1"

      - name: Step 2
        run: exit 1

      - name: Manual Intervention Approval
        id: manual_step
        if: ${{ failure() }}
        uses: actions/github-script@v5
        with:
          script: |
            const { data: { html_url: pullRequestUrl } } = await github.rest.pulls.createReviewRequest({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });
            core.setOutput('pullRequestUrl', pullRequestUrl)


      - name: Resume Step
        if: steps.manual_step.conclusion == 'success' || steps.manual_intervention_approval.outputs.pullRequestUrl
        run: echo "Resuming from manual intervention"

      - name: Automatic Step
        if: steps.manual_step.conclusion == 'failure' && !steps.manual_intervention_approval.outputs.pullRequestUrl
        run: echo "This step will run automatically when manual intervention is not required"
