name: main
on:
  workflow_dispatch:
    inputs:
      releaseEnv:
        type: choice
        description: 'What Env to release'
        required: true
        options:
          - dev
          - test
          - staging
          - prod
      version:
        required: true
  workflow_call:
    inputs:
      releaseEnv:
        type: string
        description: 'What Env to release'
        required: true
      version:
        type: string
        required: true
jobs:
  Deploy_dev:
    name: "Dev deploy - version ${{  inputs.version }} "
    environment: dev
    if: inputs.releaseEnv == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Deploying to dev
  Deploy_test:
    name: "Test deploy - version ${{  inputs.version }}"
    environment: test
    if: inputs.releaseEnv == 'test' || inputs.releaseEnv == 'prod' || inputs.releaseEnv == 'staging'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Deploying to test
  Deploy_staging:
    name: "Staging Deploy - version ${{  inputs.version }}"
    environment: staging
    if: inputs.releaseEnv == 'staging' || inputs.releaseEnv == 'prod'
    needs: [Deploy_test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Deploying to Staging
  Deploy_prod:
    name: "Prod Deploy - version ${{  inputs.version }}"
    environment: prod
    if: inputs.releaseEnv == 'prod'
    runs-on: ubuntu-latest
    needs: [Deploy_staging,Deploy_test]
    steps:
      - name: Deploy
        run: echo Deploying to prod
