name: main
on:
  workflow_dispatch:
    inputs:
      releaseEnv:
        type: environment
        description: 'What Env to release'
        required: true
jobs:
  Deploy_dev:
    name: "Dev deploy"
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Deploying to dev
  Deploy_test:
    name: "Test deploy"
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Deploying to test
  Deploy_staging:
    name: "Staging Deploy"
    environment: staging
    needs: [Deploy_test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Deploying to Staging
  Deploy_prod:
    name: "Prod Deploy"
    environment: prod
    runs-on: ubuntu-latest
    needs: [Deploy_staging]
    steps:
      - name: Deploy
        run: echo Deploying to prod
