name: My Workflow

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is step 1"

      - name: Step 2
        run: echo "This is step 2"

      - name: Additional Step for job1
        run: echo "This is an additional step for job1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - <<: *job1_steps

      - name: Additional Step for job2
        run: echo "This is an additional step for job2"

# YAML anchor definition for steps in job1
job1_steps: &job1_steps
  - name: Step 1
    run: echo "This is step 1"

  - name: Step 2
    run: echo "This is step 2"
