name: My Workflow

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: Step 1
        run: echo "This is step 1"

      - name: Step 2
        run: echo "TEST=111" >> $GITHUB_ENV
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps: 
      - name: Job 2 Step 1
        run: echo "This is step 1 from job2"

      - name: Step 2
        run: echo ${{ env.TEST }}

 
