name: test_trigger
on:
  workflow_dispatch:

jobs:
  run-cd:
    name: Run CD pipeline
    uses: ./.github/workflows/test1.yml
    with:
      releaseEnv: staging
      version: trigger_from_test.yml
